import { Box, Text, Grid, Flex } from 'theme-ui'

import rare from './images/rare.png'
import rare2x from './images/rare2x.png'

import facemask from './images/facemask.png'
import facemask2x from './images/facemask2x.png'

import flyer2 from './images/flyer2.png'

import tshirt2x from './images/tshirt2x.png'
import tshirt from './images/tshirt2x.png'

import mint from './images/mint.png'

import worldwide1 from './images/worldwide1.png'

import scalerepeat from './images/scalerepeat.png'

import uglyunicorns from './images/uglyunicorns.gif'

import goat from './images/goat.png'

import burns from './images/burns.gif'

export default function Blocks() {
    return (
        

<Flex
            sx={{
                justifyContent: 'center',
                alignItems: 'center',
                pt: [4, 4, 6],
                pb: [7, 7, 9],
                px: [3, 3, 6],
            }}
        >
            <Box sx={{ maxWidth: 1230, width: '100%' }}>

<Grid
                    columns={['1fr', '1fr', '1fr 1fr']}
                    sx={{ maxWidth: '100%' }}
                >
                    <Box
                        sx={{ bg: '#BFCE31', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ✺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                22,222{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Ugly
                                </Text>{' '}
                               Unicorns
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Each is entirely unique,
                                generated by combining attributes like fur, 
		facial traits, outfits, accessories, gradients-colors-textures. 
		With nearly endless combos, all are 
		guaranteed to be one of a kind. 

                            </Text>
                        </Box>
<Flex
                            sx={{
                                justifyContent: 'center',
                                alignItems: 'center',
                                pt: [4, 4, 0],
                                img: {
                                    maxWidth: ['60%', '60%', '100%'],
                                },
                            }}
                        >
                            <img
                                alt="uglyunicorns"
                                src={uglyunicorns}
                                height="auto"
                                width="auto"
                                srcSet={`${uglyunicorns} 2x`}
                            />
                        </Flex>
                        
                    </Box>
                    <Flex
                        sx={{
                            bg: '#F7046E',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                padding: [4, 4, 7],
                                flex: 1,
                            }}
                        >
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ✺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Secure the most{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    rare
                                </Text>{' '}
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Even though no two Ugly Unicorns will ever be the
                                same, some variations are rarer than others.
                                Watch out for special traits - the rarer the attributes, the rarer
                               they will be.
                            </Text>
                        </Box>

                        <Flex
                            sx={{
                                justifyContent: 'center',
                                alignItems: 'center',
                                pt: [4, 4, 0],
                                img: {
                                    maxWidth: ['60%', '60%', '100%'],
                                },
                            }}
                        >
                            <img
                                alt="Character"
                                src={rare}
                                height="auto"
                                width="auto"
                                srcSet={`${rare2x} 2x`}
                            />
                        </Flex>
                    </Flex>
                </Grid>

<Grid
                    columns={['1fr', '1fr', '1fr', '1fr 1fr 1fr']}
                     
                    sx={{
                        maxWidth: '100%',
                   
                        mt: 3,
                        width: '100%',
                        borderRadius: 10,}}
                >
                    <Box
                        sx={{ bg: '#ff82a2', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ✺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Build{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    With
                                </Text>{' '}
                              Us
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                              
Our aim is to develop the first ever community founded startup utilizing blockchain technology and create a fun collaborative experience with immersive utilities. Ugly Unicorns grant you entry into a members only club, the Founding Members Club, where you have a real, meaningful voice, access to several perks and gives you co-founder status. Our mission is to bring visionaries from FMC to the forefront of what we're building which is Minchyn™, a Web3 engage to earn social media platform with patent pending technology.
                            </Text>
                        </Box>

                       
                    </Box>

 <Box
                        sx={{ bg: '#c582ff', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ✺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Token{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    yielding
                                </Text>{' '}
                               
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                            Each Ugly Unicorn yields $Minchyn, $Minchyn is an erc20 token that will play a big part in our ecosystem and as well be utilized within the Minchyn engage to earn social media platform. As an added bonus, Co-founders (holders) are also gifted a S.A.F.E, Simple Agreement for Future Equity, which grants them equity in our startup as gratitude for being a visionary co-founder and supporter of our C-Corp startup.
                            </Text>
                        </Box>

                       
                    </Box>
<Box
                        sx={{ bg: '#82ff97', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ✺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                {' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Engage
                                </Text>{' '}
                               to earn
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Use your voice to help!
 
Ugly Unicorns give holders the power to influence and contribute to our evolution as a startup through an interactive and fun social platform, the founding members club. Co-founders (holders) can participate in this gamified eco-system and earn points by performing simple daily tasks like voting on who we should hire, giving feedback, making suggestions or sharing resources. We envision being a collective of visionaries scaling a startup and further adopting the foundation of Web3 as an industry.
</Text> <Text
                                as="p"
                                sx={{ fontSize: [0, 0, 1], fontStyle: 'italic', fontWeight: 100 }}> *Points can be exchanged for more $Minchyn
                            </Text>
                        </Box>

                       
                    </Box>
                     
                    
                </Grid>
                <Grid
                    columns={['1fr', '1fr', '52fr 48fr']}
                    gap={[0, 0, 2]}
                    sx={{
                        maxWidth: '100%',
                        bg: '#edc266',
                        mt: 3,
                        width: '100%',
                        borderRadius: 10,
                    }}
                >
                    <Flex
                        sx={{
                            py: [4, 4, 8],
                            pl: [4, 4, 8],
                            pr: [5, 6, 0],
                            flexDirection: 'column',
                        }}
                    >
                        <Text
                            sx={{
                                fontSize: [6, 6, 8],
                                display: 'block',
                                fontFamily: 'heading',
                                lineHeight: 1,
                                color: 'textInversedSoft',
                            }}
                        >
                            ✺
                        </Text>
                        <Text
                            sx={{
                                fontSize: [5, 5, 8],
                                lineHeight: [1.3, 1.3, 1],
                                fontFamily: 'heading',
                                display: 'block',
                                color: 'secondary',
                                mt: [0, 0, 3],
                            }}
                        >
                            Innovation & impact{' '}
                            <Text as="span" sx={{ fontStyle: 'italic' }}>
                                matters
                            </Text>{' '}
                            to us.
                        </Text>
                        <Text
                            as="p"
                            sx={{
                                fontSize: [1, 1, 2],
                                fontWeight: 300,
                                maxWidth: 486,
                                mt: [0, 0, 3],
                            }}
                        >
                          Changing how companies are founded and how products are built, together we will accomplish something never done before in making every person that mints an Ugly Unicorn a co-founder, with equity, in our startup. When Web3 enthusiast discuss the future of NFT’s, Ugly Unicorns is what they are talking about. More than art on the blockchain, each is a record of an initiated co-founder invested in supercharging a startup collectively.
                        </Text>
                    </Flex>
                    <Box
                        sx={{
                            display: ['none', 'none', 'flex'],
                            justifyContent: 'flex-end',
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                overflow: 'hidden',
                                img: {
                                    height: 'auto',
                                    width: '100%',
                                    display: 'block',
                                },
                            }}
                        >
                            <img
                                alt="Character"
                                src={facemask}
                                srcSet={`${facemask2x} 2x`}
                            />
                        </Box>
                    </Box>

                    <Box
                        sx={{
                            display: ['flex', 'flex', 'none'],
                            justifyContent: 'center',
                            alignItems: 'center',
                        }}
                    >
                        <img
                            alt="Character with face mask"
                            src={facemask}
                            height="auto"
                            width="80%"
                            srcSet={`${facemask2x} 2x`}
                        />
                    </Box>
                </Grid>     


<Flex
            sx={{
                justifyContent: 'center',
                alignItems: 'center',
                py: [8, 8, 9],
                px: [5, 5, 6],
            }}
        >
            <Box sx={{ maxWidth: 1230 }}>
                <Grid gap={1} columns={['1fr', '1fr', '1fr 1fr']}>
                    <Text
                        as="h1"
	color="#FFFFFF"
                        sx={{
                            fontFamily: 'heading',
                            fontSize: [6, 6, 8],
                            lineHeight: 1.1,
                            pr: [0, 0, 4],
                            maxWidth: 1230,
                        }}
                    >
                        Our{' '}
                        <Text as="span" color="#BFCE31" sx={{ fontStyle: 'italic' }}>
                            Roadmap
                        </Text>
                        
                    </Text>
                  <Text as="span" color="#FFFFFF" sx={{ fontWeight: 300 }}>
                            Going further together: In search of tech enthusiast who want to be at the forefront of something never done before, together we will supercharge an innovative and inclusive tech startup!


                        </Text>
                </Grid>
            </Box>
        </Flex>           
<Grid
                    columns={['1fr', '1fr', '1fr', '1fr', '1fr 1fr 1fr 1fr']}
                    sx={{ maxWidth: '100%' }}
                >  <Flex
                        sx={{
                            bg: '#66DBC0',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                    
                        <Box sx={{ padding: [4, 4, 7], flex: 1, }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❶
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                {' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Mint
                                </Text>{' '}
                               Unicorns
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                A uniquely fun collection delivering innovative, one of a kind, experiences.
                            </Text>
                        </Box>
                   
</Flex>
                    <Flex
                        sx={{
                            bg: '#0CB8EF',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                padding: [4, 4, 7],
                                flex: 1,
                            }}
                        >
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❷
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Onboard{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Members
                                </Text>{' '}
                            </Text>
		
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                              
		All holders will create a profile on the founding members club platform where they can participate in exclusive tasks and programs.
                            </Text>
                        </Box>
                    </Flex>
<Box
                        sx={{ bg: '#F7046E', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❸
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Equity{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Claims
                                </Text>{' '}
                              
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                After registering on the FMC platform holders can fill out a form on platform that allows them to claim their founder equity. After completion of the form they will recieve a S.A.F.E.
                            </Text>
                        </Box>
                    </Box>
                    <Flex
                        sx={{
                            bg: '#FFCF2F',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                padding: [4, 4, 7],
                                flex: 1,
                            }}
                        >
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❹
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Beyond the{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                     Mint 
                                </Text>{' '}
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Data room access, Exclusive E-Community, Minchyn Pitch Deck Presentation, Member Rights, Virtual Meetings, IRL Events.
                            </Text>
                        </Box>
                    </Flex>
                </Grid>
<grid><flex>UGLY BUT UNICORN. WE ARE THE FUTURE. THE FUTURE IS US. </flex></grid>

<Grid columns={['1fr', '1fr', '1fr 1fr']} 
		>
                    <Flex
                        sx={{
                            bg: '#d1d44c',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                        <Box 
                            sx={{
                                padding: [4, 4, 7],
                                flex: 1,
                            }}
                        >
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❺
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                The{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    G.O.A.T 
                                </Text>{' '}
                             
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                               To celebrate a sold out collection we'll host an IRL festival hosted by the GOAT of comedy. The event will be live streamed using patent pending tech where holders can earn ticket and stream revenues.

                            </Text>
                        </Box>
                        <Flex
                            sx={{
                                justifyContent: 'center',
                                alignItems: 'center',
                                pt: [4, 4, 0],
                                img: {
                                    maxWidth: ['60%', '60%', '40%'],
                                },
                            }}
                        >
                             <img
                                alt="goat"
                                src={goat}
                                srcSet={`${goat} 2x`}
                            />
                        </Flex>
                    </Flex>



                    <Flex
                        sx={{
                            bg: '#b99de3',
                            width: '100%',
                            borderRadius: 10,
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                padding: [4, 4, 7],
                                flex: 1,
                            }}
                        >
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❻
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                FMC member{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                     kit 
                                </Text>{' '}
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Members that mint 4 or more Ugly Unicorns will receive an exclusive gift box with physical utility items, merch and other surprises. 

                            </Text>
                        </Box>
 <Flex
                            sx={{
                                justifyContent: 'center',
                                alignItems: 'center',
                                pt: [4, 4, 0],
                                img: {
                                    maxWidth: ['100%', '100%', '100%'],
                                },
                            }}
                        >
                             <img
                                alt="kit"
                                src={burns}
                                srcSet={`${burns} 2x`}
                            />
                        </Flex>
                        
                    </Flex>
                </Grid>


                <Grid
                    columns={['1fr', '1fr', '52fr 48fr']}
                    gap={[0, 0, 2]}
                    sx={{
                        maxWidth: '100%',
                        bg: '#e0ab4f',
                        mt: 3,
                        width: '100%',
                        borderRadius: 10,
                    }}
                >
                    <Flex
                        sx={{
                            py: [4, 4, 8],
                            pl: [4, 4, 8],
                            pr: [5, 6, 0],
                            flexDirection: 'column',
                        }}
                    >
                        <Text
                            sx={{
                                fontSize: [6, 6, 8],
                                display: 'block',
                                fontFamily: 'heading',
                                lineHeight: 1,
                                color: 'textInversedSoft',
                            }}
                        >
                            ❼
                        </Text>
                        <Text
                            sx={{
                                fontSize: [5, 5, 8],
                                lineHeight: [1.3, 1.3, 1],
                                fontFamily: 'heading',
                                display: 'block',
                                color: 'textInversedSoft',
                                mt: [0, 0, 3],
                            }}
                        >
                            Use of{' '}
                            <Text as="span" sx={{ fontStyle: 'italic' }}>
                                  Funds
                            </Text>{' '}
                           
                        </Text>
                        <Text
                            as="p"
                            sx={{
                                fontSize: [1, 1, 2],
                                fontWeight: 300,
                                maxWidth: 486,
                                mt: [0, 0, 3],
                            }}
                        >
                           
✺ Hire CTO, CMO, CFO (2 Women){' '}
✺ Hire 4 Software Engineers (3 Women){' '}
✺ Product Development{' '}
✺ Product Marketing{' '}
✺ NFT Team ({'<=10%'}){' '}
✺ Remaining Capital Reserved{' '}

                        </Text>
                    </Flex>
                    <Box
                        sx={{
                            display: ['none', 'none', 'flex'],
                            justifyContent: 'flex-end',
                            flexDirection: 'column',
                        }}
                    >
                        <Box
                            sx={{
                                overflow: 'hidden',
                                img: {
                                    height: 'auto',
                                    width: '100%',
                                    display: 'block',
                                },
                            }}
                        > <Text sx={{
                               
                                color: '#e0ab4f',
                            }}>{' Minchyn UI'}</Text>
                            <img
                                alt="Character"
                                src={tshirt}
                                srcSet={`${tshirt2x} 2x`}
                            />
                        </Box>
                    </Box>

                    
                </Grid>


<Grid
                    columns={['1fr', '1fr', '1fr', '1fr 1fr 1fr']}
                     
                    sx={{
                        maxWidth: '100%',
                   
                        mt: 3,
                        width: '100%',
                        borderRadius: 10,}}
                >
                    <Box
                        sx={{ bg: '#FF82A2', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❽
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Minchyn{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                      Beta
                                </Text>{' '}
                              
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                               Minchyn Beta application soft launch available for FMC members.
                            </Text>
                        </Box>

                       
                    </Box>

 <Box
                        sx={{ bg: '#b8ff82', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❾
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Scale &{' '}
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    Repeat
                                </Text>{' '}
                               
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                  Brand marketing, product development, sweep Ugly Unicorn floor, scale, repeat.
                            </Text>
                        </Box>

                       
                    </Box>
<Box
                        sx={{ bg: '#fffd82', width: '100%', borderRadius: 10 }}
                    >
                        <Box sx={{ padding: [4, 4, 7] }}>
                            <Text
                                sx={{
                                    fontSize: [6, 6, 8],
                                    display: 'block',
                                    fontFamily: 'heading',
                                    lineHeight: 1,
                                }}
                            >
                                ❿
                            </Text>
                            <Text
                                sx={{
                                    fontSize: [5, 5, 7],
                                    lineHeight: 1.3,
                                    fontFamily: 'heading',
                                    display: 'block',
                                }}
                            >
                                Worldwide
                                <Text as="span" sx={{ fontStyle: 'italic' }}>
                                    
                                </Text>{' '}
                               
                            </Text>
                            <Text
                                as="p"
                                sx={{ fontSize: [1, 1, 2], fontWeight: 300 }}
                            >
                                Minchyn product launch and live alpha. Minchyn will be available for download worldwide!
                            </Text>
                        </Box>

                       
                    </Box>
                     
                    
                </Grid>


            </Box>
        </Flex>
    )
}
